export const uf = [
  { id: 1, uf: "AC", nomeUF: "Acre", codIbgeUF: "12" },
  { id: 2, uf: "AL", nomeUF: "Alagoas", codIbgeUF: "27" },
  { id: 3, uf: "AP", nomeUF: "Amapá", codIbgeUF: "16" },
  { id: 4, uf: "AM", nomeUF: "Amazonas", codIbgeUF: "13" },
  { id: 5, uf: "BA", nomeUF: "Bahia", codIbgeUF: "29" },
  { id: 6, uf: "CE", nomeUF: "Ceará", codIbgeUF: "23" },
  { id: 7, uf: "DF", nomeUF: "Distrito Federal", codIbgeUF: "53" },
  { id: 8, uf: "ES", nomeUF: "Espírito Santo", codIbgeUF: "32" },
  { id: 9, uf: "GO", nomeUF: "Goiás", codIbgeUF: "52" },
  { id: 10, uf: "MA", nomeUF: "Maranhão", codIbgeUF: "21" },
  { id: 11, uf: "MT", nomeUF: "Mato Grosso", codIbgeUF: "51" },
  { id: 12, uf: "MS", nomeUF: "Mato Grosso do Sul", codIbgeUF: "50" },
  { id: 13, uf: "MG", nomeUF: "Minas Gerais", codIbgeUF: "31" },
  { id: 14, uf: "PA", nomeUF: "Pará", codIbgeUF: "15" },
  { id: 15, uf: "PB", nomeUF: "Paraíba", codIbgeUF: "25" },
  { id: 16, uf: "PR", nomeUF: "Paraná", codIbgeUF: "41" },
  { id: 17, uf: "PE", nomeUF: "Pernambuco", codIbgeUF: "26" },
  { id: 18, uf: "PI", nomeUF: "Piauí", codIbgeUF: "22" },
  { id: 19, uf: "RN", nomeUF: "Rio Grande do Norte", codIbgeUF: "24" },
  { id: 20, uf: "RS", nomeUF: "Rio Grande do Sul", codIbgeUF: "43" },
  { id: 21, uf: "RJ", nomeUF: "Rio de Janeiro", codIbgeUF: "33" },
  { id: 22, uf: "RO", nomeUF: "Rondônia", codIbgeUF: "11" },
  { id: 23, uf: "RR", nomeUF: "Roraima", codIbgeUF: "14" },
  { id: 24, uf: "SC", nomeUF: "Santa Catarina", codIbgeUF: "42" },
  { id: 25, uf: "SP", nomeUF: "São Paulo", codIbgeUF: "35" },
  { id: 26, uf: "SE", nomeUF: "Sergipe", codIbgeUF: "28" },
  { id: 27, uf: "TO", nomeUF: "Tocantins", codIbgeUF: "17" }
]
